### ISSUE TITLE
own phrase for menu tab

### ISSUE THREAD

**Issue by cmdtstof** [eprints/irstats2#31]
**\* enhancement ***
s.a. issue #23 

the menu tab "statistics" should not be changed when a statistic report is choosen.

please add a new phrase for the menu tab OR do not change the menu tab when choosing a report at all.

since the phrase for the menu tab AND the title (class="pageTitle") is the same, title will show "statistics" when chaning "most_popular_authors" to "statistic". this is not very helpfull.

thanks

**Comment by jiadiyao** [comment]
Resolved in #74
