### ISSUE TITLE
ignoring local ip ranges in irstats2

### ISSUE THREAD

**Issue by sjbrownrigg** [eprints/irstats2#50]
Hi,

Are there settings for ignoring ip ranges, say for example local/developer ip addresses?

Many thanks,
Stewart

**Comment by ctgraham** [comment]
This goes beyond just local IPs and should include bad robots by IP.  See also: https://wiki.eprints.org/w/Robots

**Comment by ctgraham** [comment]
C.f. https://github.com/eprints/irstats2/pull/86
C.f. https://github.com/eprints/irstats2/pull/82

@jiadiyao, can you tag the PR or commit which superseded these PRs closed as duplicates?

**Comment by jiadiyao** [comment]
Here it is: 
https://github.com/eprints/irstats2/commit/8a769837c83677df42ebcee832cae1bc1db1fc1e

To filter out locally defined ip addresses, add the following to your z_irstats2.pl:

$c->{irstats2}->{robot_ips} = [
       "180.76.15.34",
       "123.125.71",
        ];

**Comment by ctgraham** [comment]
So can this issue be closed?
