### ISSUE TITLE
"Filter items" may return wrong result set

### ISSUE THREAD

**Issue by sebastfr** [eprints/irstats2#60]
Scenario: user wants to filter by author named "Anderson" and the minimum number of chars before a query is performed/sent to the server is 3.

As the user is typing "anderson", this is the chain of events:

1- query for 'and'
2- query for 'ande'
3- query for 'ander'
4 - etc.

Since query 1 may take longer to return (cos it will match more results than #2 and #3), its results may get inserted on the page AFTER queries #2 and #3 have returned. So this displays wrong results.

We need a JS timer that doesn't send a query if the user is still typing. Tim Brody has developed such code for EPrints but not sure in which context. It's in a JS file somewhere in the core code.

**Comment by jiadiyao** [comment]
Can not reproduce.
