### ISSUE TITLE
Stat::Export::Csv exposes the csv data fields not always in the same order within the same extraction

### ISSUE THREAD

**Issue by eniocarboni** [eprints/irstats2#72]
In "`sub export`" you use "`keys %$header`" but you should use an ordered form like "`sort keys %$header`".
Same thing in "`keys %$data`" but you should use an ordered form like "`sort keys %$data`".
The first is on line 26 and the second is on line 33 on package `EPrints::Plugin::Stats::Export::CSV`.

Update the mimetype from text/plain to text/csv will be greatly appreciated (see issue #68   ).

**Comment by sebastfr** [comment]
Hello, could you do a Pull Request, and hopefully someone at EPrints (Services) will be able to merge it.

**Comment by mpbraendle** [comment]
Unfortunately, we can't  - since the code in this repo is missing.

**Comment by sebastfr** [comment]
Can't you access: https://github.com/eprints/irstats2/blob/master/cfg/plugins/EPrints/Plugin/Stats/Export/CSV.pm

?

**Comment by mpbraendle** [comment]
The Bazaar package puts those things into lib/plugins/...  That's why I did not find it here.

**Comment by zuphilip** [comment]
Any news on this issue? Can this been fixed soon?

**Comment by eniocarboni** [comment]
I think sebastfr has already merged this on master at 9 Mar 2016 as you can see on https://github.com/eprints/irstats2/pull/73 even if this issue is still open

**Comment by zuphilip** [comment]
Okay, thank you for the information. It seems that this is not contained in the latest release on bazaar (deposited 08 Jul 2014 12:24): http://bazaar.eprints.org/365/ . Can someone create a new release in bazaar with this fix?

**Comment by jiadiyao** [comment]
A new bazaar package will be released soon.
