### ISSUE TITLE
Sets must be possible over multiple fields

### ISSUE THREAD

**Issue by mpbraendle** [eprints/irstats2#76]
It should be possible to define a single set over multiple fields of the same type:

E.g. 

$c->{irstats2}->{sets} = [
{
                'name' => 'authors',
                'field' => [ 'creators', 'editors' ]
}
];

**Comment by jiadiyao** [comment]
You could define a new automatic field to merge the creators and editors, then define the irstats2 set over this new field.

**Comment by mpbraendle** [comment]
Thanks Jiadi. I was thinking of a virtual field, but automatic seems to be better. As far as I understand, automatic fields are filled upon modification, aren't they? That would require to recalculate them for already existing eprints.
You can close the issue.

**Comment by jiadiyao** [comment]
_automatic fields are filled upon modification, aren't they?_ 
Yes, they are. 
You can re-calculate all automatic fields by: 
epadmin recommit *repository_id* *dataset_id* [*eprint_id* *eprint_id* ...]
            Recommit all the records in the given dataset. What this does is
            cause the automatic values to be re-calculated. If a list of
            eprint_ids is given then just recommit those.
