### ISSUE TITLE
CGIs expose XSS vulnerabilities

### ISSUE THREAD

**Issue by ctgraham** [eprints/irstats2#80]
There are several instances of unchecked user-entered variables which are passed back out in the CGIs:
https://github.com/eprints/irstats2/blob/c66d56edc79c5daf80deced9163c2c6b7bd840b2/cgi/stats/export#L40
https://github.com/eprints/irstats2/blob/c66d56edc79c5daf80deced9163c2c6b7bd840b2/cgi/stats/get#L42
https://github.com/eprints/irstats2/blob/c66d56edc79c5daf80deced9163c2c6b7bd840b2/cgi/stats/set_finder#L94
This exposes the potential for cross site scripting.

**Comment by graingert** [comment]
probably better to use a safe by default template processor: https://metacpan.org/pod/Text::Caml
