### ISSUE TITLE
Possible XSS vulnerability in Google::Graph

### ISSUE THREAD

**Issue by Ainmhidh** [eprints/irstats2#89]
Value for graph_type output as part of json response without encoding - potentially vulnerable to content-sniffing browser?

**Comment by graingert** [comment]
would it be a good idea to set `X-Content-Type-Options: nosniff`

**Comment by drn05r** [comment]
Subsequently fixed by `EPrints::Plugin::Stats::Utils::validate_non_context_param` in 877a322
