### ISSUE TITLE
cannot install irstats2 from bazaar

### ISSUE THREAD

**Issue by chairik** [eprints/irstats2#92]
Hi, I am new to eprints (EPrints Release: | 3.3.15) and I tried to install the irstats2 from the bazaar and I got this error. 
> Error operating on /usr/share/eprints3/lib/lang/es/phrases/: Permission denied

The interesting is that the ./es/   folder does not exist. I had installed ES language package but after some days I removed it.

What is the problem and how to install irstats2?

Thank you in advance

**Comment by jesusbagpuss** [comment]
Hi @chairik ,
Can I check the following: 
In `[EPRINTS_ROOT]/archives/[ARCHIVEID]/cfg/cfg.d/languages.pl` (or any other file in the `cfg.d` directory), what is specified for this config:

```perl
$c->{defaultlanguage} = 'en';
$c->{languages} = [ 'en' ];
```
I think if there is a reference to 'es' in either of these, it might make the plugin try to find other language directories.

If you can't see any reference to 'es' in these, what does the output of:
`[EPRINTS_ROOT]/bin/epadmin test`
return?

**Comment by chairik** [comment]
Thank you for your fast answer @jesusbagpuss 
`languages.pl` is the same as you mentioned.

when i run `epadmin test`, I get this result

```
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = "en_US:en",
	LC_ALL = (unset),
	LC_CTYPE = "UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_US.UTF-8").
\C is deprecated in regex; marked by <-- HERE in m/(\C <-- HERE )/ at /usr/share/eprints3/bin/../perl_lib/URI/Escape.pm line 205.
Failed to parse XML file: /usr/share/eprints3/archives/my_repo/cfg/lang/en/phrases/views.xml: Empty Stream at /usr/share/eprints3/bin/../perl_lib/EPrints/XML/LibXML.pm line 114.
 (/usr/share/eprints3/lib/)
Error loading /usr/share/eprints3/archives/my_repo/cfg/lang/en/phrases/views.xml
Everything seems OK.
```

What i have to do?

**Comment by jesusbagpuss** [comment]
Hi,
The first thing I would check is this file:
/usr/share/eprints3/archives/my_repo/cfg/lang/en/phrases/views.xml
if it's just an empty file, I would either remove it, or rename it something like 'views.xml.empty'.
If there is XML in it, I would try validating it - maybe with:
`>xmllint --format /usr/share/eprints3/archives/my_repo/cfg/lang/en/phrases/views.xml`
if this fails, it will show you where the bad XML is.

When you tried to install IRStats, was this from the web interface?
If so, have you restarted Apache since removing the 'es' language pack?

If you haven't restarted Apache. it might be worth doing this - when it loads, it keeps information about files - and it might still expect the 'es' folder to be there.

I think the warnings about locale are a different problem (this might help: https://stackoverflow.com/questions/2499794/how-to-fix-a-locale-setting-warning-from-perl - but I haven't seen that before).

Let me know how you get on!

**Comment by chairik** [comment]
The `views.xml`, it was empty and i removed it, now and i dont get anymore this warning.
For the **warnings about locale** i still try to find an answer, and now i will check your suggestion.

For the IRStats, 
1. I tried it from the web interface of the bazaar of the eprints, i could not find instructions for manual installation.
2. I restarted many times my apache with these command:
-  `sudo services apache2 restart`
-  `sudo apache2ctl restart`

But, I still get the same error.

**Comment by jesusbagpuss** [comment]
OK - I'm trying to work out the best way to find the problem.
Does the following folder exist:
[EPRINTS_ROOT]/archives/[ARCHIVEID]/cfg/lang/es/

If you have a version of grep that supports regular-expression searching, you could try something like this (from the EPRINTS_ROOT directory):
`grep -e '\bes\b' perl_lib/EPrints lib archives/ARCHIVEID/cfg/`
This will find something in `perl_lib/EPrints/Utils.pm`, but what else (if anything) does it find?

There *is* a way to install Bazaar packages from the command-line - but I think trying to find out the main problem here is more sensible to start with - it will only come back to cause problems in the future!

**Comment by chairik** [comment]
this folder `[EPRINTS_ROOT]/archives/[ARCHIVEID]/cfg/lang/es/` does not exist.

the `grep` command that you provide me it gives this:
```
/cfg/
grep: perl_lib/EPrints: No such file or directory
grep: lib: No such file or directory
grep: archives/ARCHIVEID/cfg/: No such file or directory
```
I also found that the `perl_lib/EPrints/Utils.pm` exist.

Now what i am doing?

**Comment by jesusbagpuss** [comment]
Hi,
try this (based on the paths shown in your first post - and the info above - it looks like the grep command wasn't run from /usr/share/eprints3/ ?). I also forgot to put the `-r` flag on the grep - so it looks into the sub-directories.
```
> cd /usr/share/eprints3
> grep -r -e '\bes\b' perl_lib/EPrints lib cfg archives/my_repo/cfg
```

**Comment by chairik** [comment]
I was in the root of the eprints, as you say, now it gives this:
```
perl_lib/EPrints/Utils.pm:		if( $in eq "y" ) { print wrap_text( "es" ); }
lib/epm/flag_pack/flag_pack.epmi:          <filename>static/images/flags/es.png</filename>
lib/epm/flag_pack/flag_pack.epm:          <filename>static/images/flags/es.png</filename>
lib/epm/apw_branding/apw_branding.epm:AUfpHnC0T8+S2BJFqBTGN+Nz+jBIoOh1phxMAB3HY7NX1MdAQgDG/FQa612G024AxsLH7Nl5S/es
Binary file lib/themes/apw_themes/static/apw_template/fonts/fontawesome-webfont.woff matches
Binary file lib/themes/apw_themes/static/apw_template/fonts/fontawesome-webfont.woff2 matches
Binary file lib/static/flowplayer-3.2.1.swf matches
Binary file lib/static/flowplayer.swf matches
Binary file lib/static/images/epm/unknown.png matches
Binary file lib/static/images/epm/flag_pack.png matches
Binary file lib/static/images/flags/za.png matches
Binary file lib/static/images/gnu-head-sm.jpg matches
Binary file lib/static/style/images/logo_background.png matches
lib/mime.types:application/ecmascript				es
lib/mime.types:video/mp4v-es
lib/defaultcfg/namedsets/languages:es
grep: archives/ARCHIVEID/cfg/: No such file or directory

```

**Comment by jesusbagpuss** [comment]
> grep: archives/ARCHIVEID/cfg/: No such file or directory
You should change 'ARCHIVEID' to your archive id - from your first post, this might be 'my_repo' - but it might be something else?

You could try:
```
> grep -r -e '\bes\b' archives/*/cfg/ 
```
if you have more than one archive.

**Comment by chairik** [comment]
Now gives this:
`archives/my_repo/cfg/namedsets/languages:es`

**Comment by jesusbagpuss** [comment]
Ok... I'm still a bit puzzled.
What is in: [EPRINTS_ROOT]/lib/epm/?

**Comment by jesusbagpuss** [comment]
Aaaah!
I think i've sussed it out!
Looking at the files here: http://bazaar.eprints.org/512/
There is: `lang/es/phrases/irstats2.xml`.
It's not a problem with you un-installing the ES language pack - it's because IRStats *is* trying to install an ES file!

If you:
```
> mkdir [EPRINTS_ROOT]/lib/lang/es/
```
and then try to install the file, it should be OK!

**Comment by chairik** [comment]
this 3 folders `apw_branding  flag_pack  irstats2`

**Comment by chairik** [comment]
ok, we had a progress but now i get this error
`Error operating on /usr/share/eprints3/lib/lang/es/phrases/irstats2.xml: Permission denied`

**Comment by jesusbagpuss** [comment]
This sounds like a permission error.
Which user is Apache running as?
What are the permissions on the `[EPRINTS_ROOT]/lib/lang/es/` directory?
Are the same as e.g. `[EPRINTS_ROOT]/lib/plugins/`?

**Comment by chairik** [comment]
Yes i believe that the problem is in the permission, but i am not sure, what exactly.
```
drwxrwxr-x  5 kstavrog my_username  4096 Mar  8 16:36 lang
drwxrwsr-x  3 www-data www-data  4096 Mar  7 15:27 plugins
drwxr-xr-x  3 root     root     4096 Mar  8 16:39 es
```

**Comment by jesusbagpuss** [comment]
Aah, we're close to solving it!
The directories (and files) should all be owned by the user that Apache runs as.
This looks like it might be 'www-data'.

If this is the case, you can change the ownership to 'www-data' for all of them, and it should then work.

I'm not sure what process you followed to install EPrints (it depends on whether your server is e.g. CentOS, Ubuntu etc.).
The guide here: https://wiki.eprints.org/w/Installing_EPrints_3_on_Debian#Create_an_.27eprints.27_system_user for debian suggests setting up an 'eprints' user, and adding www-data to it's group.

The method you used to install EPrints may have done some of this itself.

More useful info may be here:
https://wiki.eprints.org/w/Category:Installation

**Comment by chairik** [comment]
Hi,

I tried to change the owner of the folders without any positive results, but the problem was solved when i change the  folder permission to 777. Now i have installed the plugin.
**@jesusbagpuss** thank you very much for your instructions.

Now one last question, i enabled the plugin but does not appear in the menu bar, how to make it appear?

Thank you again @jesusbagpuss

**Comment by jesusbagpuss** [comment]
Hi,
I would not recommend leaving the folder permission at 777 - this allows anyone who gets onto your server to do stuff in there!

The notes here; http://eprints.github.io/irstats2/install.html might be the next thing to read - the 'Processing' section at the end might be what you really need?

**Comment by chairik** [comment]
Thank you very much everything is ok now. The problem was at the folder permissions.

Thanks
