### ISSUE TITLE
Does this line make any sense? Should it be irs2report?

### ISSUE THREAD

**Issue by jesusbagpuss** [eprints/irstats2#96]
https://github.com/eprints/irstats2/blob/74ce563ff855f7ba9702c4cd98532e95a17166a3/lib/plugins/EPrints/Plugin/Stats/View/ReportHeader.pm#L208

At the start of the `EPrints::Plugin::Stats::Context` module, a context field of `irs2report` is defined.

This is referenced a few times in the code.
The above line uses `ir2report`, and this appears only once in the code. I think it's a typo..?

**Comment by mpbraendle** [comment]
Think that, too. It occurs only once in the complete package.
